<?php

include("../functions/functions_valida_email.php");
include("../functions/functions_valida_senha.php");
include("../functions/functions_valida_nome.php");
include("../functions/functions_valida_cpf.php");
include("../functions/functions_valida_nascimento.php");
include("../functions/functions_valida_cep.php");
include("../functions/functions_enviar_email.php");
include("../functions/functions_redefinir_senha.php");
include("../functions/functions_pegar_uid.php");
include("../functions/functions_monta_timestamp.php");
include("../functions/functions_user_imagem.php");
include("../functions/functions_email_cadastro.php");
include("../functions/functions_caracter_especial.php");
include("../functions/functions_registra_termo_politica.php");
include("../functions/functions_email_verifica.php");
include("../functions/functions_pegar_procon.php");
include("../functions/functions_pegar_ind_msg_pai.php");
include("../functions/functions_status_mensagem.php");
include("../functions/functions_mascara_mensagem_tipo.php");
include("../functions/functions_ajusta_data.php");
