<?php
	@include("../functions/functions_valida_email.php");
	@include("../functions/functions_valida_senha.php");
	@include("../functions/functions_valida_nome.php");
	@include("../functions/functions_valida_cpf.php");
	@include("../functions/functions_redefinir_senha.php");
	@include("../functions/functions_enviar_email.php");
	@include("../functions/functions_pegar_uid.php");
	@include("../functions/functions_monta_timestamp.php");
?>