<?php
	include("../config/headers.php");
	include("../config/defines.php");
	include("../config/connect.php");
	include("../config/query.php");
	include("../functions/functions.php");
	include("../config/token.php");
	include("../config/vars.php");
	include("../config/mensagens.php");
?>